CC=gcc
CFLAGS=-Wall -Werror -Wextra -Wpedantic -std=c18

.PHONY: all clean

all: s08e01 s08e05
ARGS=

s08e01: s08e01.c

run: s08e01
	./s08e01 $(ARGS)

ARGS=

s08e05: s08e05.c

run: s08e05
	./s08e05 $(ARGS)
clean:
	rm s08e01 s08e05
